# Generated by Django 3.1.2 on 2021-02-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
