# Generated by Django 3.1.2 on 2021-02-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
