# Generated by Django 3.1.2 on 2021-02-04 07:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountpiggy', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='여행이름')),
                ('max_number_of_members', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)], verbose_name='여행 인원수')),
                ('start_date', models.DateTimeField(verbose_name='여행시작날짜')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='여행종료 날짜')),
                ('users', models.ManyToManyField(related_name='participating_room_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
