# Generated by Django 3.1.2 on 2021-02-05 11:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountpiggy', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='여행종료 날짜'),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(verbose_name='여행시작날짜'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('purpose', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose_category', models.CharField(choices=[('no', 'not selected'), ('et', 'etc'), ('sl', 'sleeping'), ('tr', 'transportaion'), ('fo', 'food'), ('dr', 'drink')], max_length=2)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('expend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expend_expense_set', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_set', to='accountpiggy.room')),
                ('users', models.ManyToManyField(related_name='participated_expense_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
