# Generated by Django 3.1.2 on 2021-02-06 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountpiggy', '0005_auto_20210205_2003'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.CreateModel(
            name='IndexedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='indexed_users',
            field=models.ManyToManyField(related_name='participating_room_list', to='accountpiggy.IndexedUser'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expend_expense_set', to='accountpiggy.indexeduser'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='users',
            field=models.ManyToManyField(related_name='participated_expense_set', to='accountpiggy.IndexedUser'),
        ),
    ]
