# Generated by Django 3.1.2 on 2021-02-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountpiggy', '0006_auto_20210206_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='indexed_users',
        ),
        migrations.AddField(
            model_name='indexeduser',
            name='isAdminUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indexeduser',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indexed_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
