# Generated by Django 3.1.2 on 2021-02-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0008_indexeduser_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_number_of_members',
        ),
    ]
