# Generated by Django 3.1.2 on 2021-02-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0009_remove_room_max_number_of_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexeduser',
            old_name='isAdminUser',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='indexeduser',
            name='nickname',
            field=models.CharField(default='nickname', max_length=30),
        ),
        migrations.AlterField(
            model_name='indexeduser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accountpiggy.room'),
        ),
    ]
