# Generated by Django 3.1.2 on 2021-02-07 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0010_auto_20210207_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpiggy.room')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseMatrixEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpiggy.expensematrix', verbose_name='정산 행렬')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='accountpiggy.indexeduser', verbose_name='받을 사람')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='accountpiggy.indexeduser', verbose_name='보내야 하는 사람')),
            ],
        ),
    ]
