# Generated by Django 3.1.2 on 2021-02-07 14:53

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0011_expensematrix_expensematrixentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='쓴시간'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expend_expense_set', to='accountpiggy.indexeduser', verbose_name='돈쓴자'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purpose',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='용도'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purpose_category',
            field=models.CharField(choices=[('no', 'not selected'), ('et', 'etc'), ('sl', 'sleeping'), ('tr', 'transportaion'), ('fo', 'food'), ('dr', 'drink')], max_length=2, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='expensematrix',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountpiggy.room'),
        ),
    ]
