# Generated by Django 3.1.2 on 2021-02-08 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0012_auto_20210207_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensematrixentry',
            name='is_cleaned_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expensematrixentry',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액'),
        ),
    ]
