# Generated by Django 3.1.2 on 2021-02-10 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountpiggy', '0013_auto_20210208_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexedUser',
            new_name='Member',
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='purpose_category',
            field=models.CharField(choices=[('no', '선택안함'), ('et', '기타'), ('sl', '숙소'), ('tr', '교통'), ('fo', '식사'), ('dr', '(기호식품) ex)술/커피')], max_length=2, verbose_name='카테고리'),
        ),
    ]
