# Generated by Django 3.1.2 on 2021-02-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0015_auto_20210210_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnteringQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.CharField(max_length=10, verbose_name='질문')),
                ('A', models.CharField(max_length=10, verbose_name='답변')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpiggy.room')),
            ],
        ),
    ]
