# Generated by Django 3.1.2 on 2021-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpiggy', '0016_enteringqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enteringqa',
            name='A',
            field=models.CharField(default='탱구리', max_length=10, verbose_name='답변'),
        ),
        migrations.AlterField(
            model_name='enteringqa',
            name='Q',
            field=models.CharField(default='요이', max_length=10, verbose_name='질문'),
        ),
    ]
